// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: domain/astree.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Language the enum type of programming languages.
type Language int32

const (
	Language_NoLang     Language = 0  // unknown language
	Language_C          Language = 1  // C
	Language_Cpp        Language = 2  // C++
	Language_Dart       Language = 3  // Dart
	Language_Java       Language = 4  // Java
	Language_Kotlin     Language = 5  // Kotlin
	Language_Scala      Language = 6  // Scala
	Language_Go         Language = 7  // Golang
	Language_Python     Language = 8  // Python
	Language_ObjectiveC Language = 9  // Objective-C
	Language_Swift      Language = 10 // Swift
	Language_Javascript Language = 11 // JavaScript
	Language_Typescript Language = 12 // TypeScript
	Language_Ruby       Language = 13 // Ruby
	Language_Rust       Language = 14 // Rust
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0:  "NoLang",
		1:  "C",
		2:  "Cpp",
		3:  "Dart",
		4:  "Java",
		5:  "Kotlin",
		6:  "Scala",
		7:  "Go",
		8:  "Python",
		9:  "ObjectiveC",
		10: "Swift",
		11: "Javascript",
		12: "Typescript",
		13: "Ruby",
		14: "Rust",
	}
	Language_value = map[string]int32{
		"NoLang":     0,
		"C":          1,
		"Cpp":        2,
		"Dart":       3,
		"Java":       4,
		"Kotlin":     5,
		"Scala":      6,
		"Go":         7,
		"Python":     8,
		"ObjectiveC": 9,
		"Swift":      10,
		"Javascript": 11,
		"Typescript": 12,
		"Ruby":       13,
		"Rust":       14,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_astree_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_domain_astree_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{0}
}

// ASTNodeType the types of syntax node (ASTNode).
type ASTNodeType int32

const (
	// Unified syntax types
	ASTNodeType_UastSyntaxError    ASTNodeType = 0
	ASTNodeType_UastTransitionUnit ASTNodeType = 1
	ASTNodeType_UastIdentifier     ASTNodeType = 2
	ASTNodeType_UastLiteral        ASTNodeType = 3
	ASTNodeType_UastKeyword        ASTNodeType = 4
	ASTNodeType_UastPunctuator     ASTNodeType = 5
)

// Enum value maps for ASTNodeType.
var (
	ASTNodeType_name = map[int32]string{
		0: "UastSyntaxError",
		1: "UastTransitionUnit",
		2: "UastIdentifier",
		3: "UastLiteral",
		4: "UastKeyword",
		5: "UastPunctuator",
	}
	ASTNodeType_value = map[string]int32{
		"UastSyntaxError":    0,
		"UastTransitionUnit": 1,
		"UastIdentifier":     2,
		"UastLiteral":        3,
		"UastKeyword":        4,
		"UastPunctuator":     5,
	}
)

func (x ASTNodeType) Enum() *ASTNodeType {
	p := new(ASTNodeType)
	*p = x
	return p
}

func (x ASTNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASTNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_astree_proto_enumTypes[1].Descriptor()
}

func (ASTNodeType) Type() protoreflect.EnumType {
	return &file_domain_astree_proto_enumTypes[1]
}

func (x ASTNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASTNodeType.Descriptor instead.
func (ASTNodeType) EnumDescriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{1}
}

// ASTEdgeType the types of syntax node relations (ASTEdge).
type ASTEdgeType int32

const (
	// Unified syntax relations
	ASTEdgeType_UastParentChild ASTEdgeType = 0
)

// Enum value maps for ASTEdgeType.
var (
	ASTEdgeType_name = map[int32]string{
		0: "UastParentChild",
	}
	ASTEdgeType_value = map[string]int32{
		"UastParentChild": 0,
	}
)

func (x ASTEdgeType) Enum() *ASTEdgeType {
	p := new(ASTEdgeType)
	*p = x
	return p
}

func (x ASTEdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASTEdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_astree_proto_enumTypes[2].Descriptor()
}

func (ASTEdgeType) Type() protoreflect.EnumType {
	return &file_domain_astree_proto_enumTypes[2]
}

func (x ASTEdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASTEdgeType.Descriptor instead.
func (ASTEdgeType) EnumDescriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{2}
}

// ASTFile combines the source content and syntax tree parsed from.
type ASTFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"` // the code content to be parsed
	Tree          *ASTree                `protobuf:"bytes,2,opt,name=Tree,proto3" json:"Tree,omitempty"`     // syntax tree parsed from Source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTFile) Reset() {
	*x = ASTFile{}
	mi := &file_domain_astree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTFile) ProtoMessage() {}

func (x *ASTFile) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTFile.ProtoReflect.Descriptor instead.
func (*ASTFile) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{0}
}

func (x *ASTFile) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ASTFile) GetTree() *ASTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

// Source models the source code content in program.
type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoDir       *string                `protobuf:"bytes,1,opt,name=RepoDir,proto3,oneof" json:"RepoDir,omitempty"`                   // repository root directory path
	FilePath      *string                `protobuf:"bytes,2,opt,name=FilePath,proto3,oneof" json:"FilePath,omitempty"`                 // relative path of source file to the repo directory
	Language      Language               `protobuf:"varint,3,opt,name=Language,proto3,enum=domain.Language" json:"Language,omitempty"` // language of the source code to be analyzed
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`                         // source code content to be analyzed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_domain_astree_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetRepoDir() string {
	if x != nil && x.RepoDir != nil {
		return *x.RepoDir
	}
	return ""
}

func (x *Source) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *Source) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_NoLang
}

func (x *Source) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ASTree the unified model of abstract syntax tree (AST).
type ASTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      Language               `protobuf:"varint,1,opt,name=Language,proto3,enum=domain.Language" json:"Language,omitempty"` // language of the syntax tree content
	Root          *ASTNode               `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`                               // root node
	Nodes         []*ASTNode             `protobuf:"bytes,3,rep,name=Nodes,proto3" json:"Nodes,omitempty"`                             // nodes in the syntax tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTree) Reset() {
	*x = ASTree{}
	mi := &file_domain_astree_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTree) ProtoMessage() {}

func (x *ASTree) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTree.ProtoReflect.Descriptor instead.
func (*ASTree) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{2}
}

func (x *ASTree) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_NoLang
}

func (x *ASTree) GetRoot() *ASTNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ASTree) GetNodes() []*ASTNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// ASTNode represents a syntax node in ASTree, denoting a structural code snippet.
type ASTNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                             // index of the node in ASTree.Nodes
	Type          ASTNodeType            `protobuf:"varint,2,opt,name=Type,proto3,enum=domain.ASTNodeType" json:"Type,omitempty"` // syntax node type
	Pos           *Position              `protobuf:"bytes,3,opt,name=Pos,proto3" json:"Pos,omitempty"`                            // start position
	End           *Position              `protobuf:"bytes,4,opt,name=End,proto3" json:"End,omitempty"`                            // end position
	Text          *string                `protobuf:"bytes,5,opt,name=Text,proto3,oneof" json:"Text,omitempty"`                    // text of the node source
	Parent        *ASTEdge               `protobuf:"bytes,6,opt,name=Parent,proto3" json:"Parent,omitempty"`                      // edge from its parent to this node
	Children      []*ASTEdge             `protobuf:"bytes,7,rep,name=Children,proto3" json:"Children,omitempty"`                  // edge(s) from this node to its children
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTNode) Reset() {
	*x = ASTNode{}
	mi := &file_domain_astree_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTNode) ProtoMessage() {}

func (x *ASTNode) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTNode.ProtoReflect.Descriptor instead.
func (*ASTNode) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{3}
}

func (x *ASTNode) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ASTNode) GetType() ASTNodeType {
	if x != nil {
		return x.Type
	}
	return ASTNodeType_UastSyntaxError
}

func (x *ASTNode) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ASTNode) GetEnd() *Position {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ASTNode) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *ASTNode) GetParent() *ASTEdge {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ASTNode) GetChildren() []*ASTEdge {
	if x != nil {
		return x.Children
	}
	return nil
}

// Position denotes a character point in the source code content.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"` // offset of the character in the string content
	Line          uint32                 `protobuf:"varint,2,opt,name=Line,proto3" json:"Line,omitempty"`     // line number of the position, starting from 1
	Column        uint32                 `protobuf:"varint,3,opt,name=Column,proto3" json:"Column,omitempty"` // column number of the position, starting from 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_domain_astree_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Position) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// ASTEdge the edge linking from parent to one of its child.
type ASTEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        uint32                 `protobuf:"varint,1,opt,name=Parent,proto3" json:"Parent,omitempty"`                     // index of parent node in the edge
	Child         uint32                 `protobuf:"varint,2,opt,name=Child,proto3" json:"Child,omitempty"`                       // index of child node in the edge
	Type          ASTEdgeType            `protobuf:"varint,3,opt,name=Type,proto3,enum=domain.ASTEdgeType" json:"Type,omitempty"` // type of relations between Parent and Child
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTEdge) Reset() {
	*x = ASTEdge{}
	mi := &file_domain_astree_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTEdge) ProtoMessage() {}

func (x *ASTEdge) ProtoReflect() protoreflect.Message {
	mi := &file_domain_astree_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTEdge.ProtoReflect.Descriptor instead.
func (*ASTEdge) Descriptor() ([]byte, []int) {
	return file_domain_astree_proto_rawDescGZIP(), []int{5}
}

func (x *ASTEdge) GetParent() uint32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *ASTEdge) GetChild() uint32 {
	if x != nil {
		return x.Child
	}
	return 0
}

func (x *ASTEdge) GetType() ASTEdgeType {
	if x != nil {
		return x.Type
	}
	return ASTEdgeType_UastParentChild
}

var File_domain_astree_proto protoreflect.FileDescriptor

const file_domain_astree_proto_rawDesc = "" +
	"\n" +
	"\x13domain/astree.proto\x12\x06domain\"U\n" +
	"\aASTFile\x12&\n" +
	"\x06Source\x18\x01 \x01(\v2\x0e.domain.SourceR\x06Source\x12\"\n" +
	"\x04Tree\x18\x02 \x01(\v2\x0e.domain.ASTreeR\x04Tree\"\xa9\x01\n" +
	"\x06Source\x12\x1d\n" +
	"\aRepoDir\x18\x01 \x01(\tH\x00R\aRepoDir\x88\x01\x01\x12\x1f\n" +
	"\bFilePath\x18\x02 \x01(\tH\x01R\bFilePath\x88\x01\x01\x12,\n" +
	"\bLanguage\x18\x03 \x01(\x0e2\x10.domain.LanguageR\bLanguage\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContentB\n" +
	"\n" +
	"\b_RepoDirB\v\n" +
	"\t_FilePath\"\x82\x01\n" +
	"\x06ASTree\x12,\n" +
	"\bLanguage\x18\x01 \x01(\x0e2\x10.domain.LanguageR\bLanguage\x12#\n" +
	"\x04Root\x18\x02 \x01(\v2\x0f.domain.ASTNodeR\x04Root\x12%\n" +
	"\x05Nodes\x18\x03 \x03(\v2\x0f.domain.ASTNodeR\x05Nodes\"\x82\x02\n" +
	"\aASTNode\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12'\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x13.domain.ASTNodeTypeR\x04Type\x12\"\n" +
	"\x03Pos\x18\x03 \x01(\v2\x10.domain.PositionR\x03Pos\x12\"\n" +
	"\x03End\x18\x04 \x01(\v2\x10.domain.PositionR\x03End\x12\x17\n" +
	"\x04Text\x18\x05 \x01(\tH\x00R\x04Text\x88\x01\x01\x12'\n" +
	"\x06Parent\x18\x06 \x01(\v2\x0f.domain.ASTEdgeR\x06Parent\x12+\n" +
	"\bChildren\x18\a \x03(\v2\x0f.domain.ASTEdgeR\bChildrenB\a\n" +
	"\x05_Text\"N\n" +
	"\bPosition\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\rR\x06Offset\x12\x12\n" +
	"\x04Line\x18\x02 \x01(\rR\x04Line\x12\x16\n" +
	"\x06Column\x18\x03 \x01(\rR\x06Column\"`\n" +
	"\aASTEdge\x12\x16\n" +
	"\x06Parent\x18\x01 \x01(\rR\x06Parent\x12\x14\n" +
	"\x05Child\x18\x02 \x01(\rR\x05Child\x12'\n" +
	"\x04Type\x18\x03 \x01(\x0e2\x13.domain.ASTEdgeTypeR\x04Type*\xb4\x01\n" +
	"\bLanguage\x12\n" +
	"\n" +
	"\x06NoLang\x10\x00\x12\x05\n" +
	"\x01C\x10\x01\x12\a\n" +
	"\x03Cpp\x10\x02\x12\b\n" +
	"\x04Dart\x10\x03\x12\b\n" +
	"\x04Java\x10\x04\x12\n" +
	"\n" +
	"\x06Kotlin\x10\x05\x12\t\n" +
	"\x05Scala\x10\x06\x12\x06\n" +
	"\x02Go\x10\a\x12\n" +
	"\n" +
	"\x06Python\x10\b\x12\x0e\n" +
	"\n" +
	"ObjectiveC\x10\t\x12\t\n" +
	"\x05Swift\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"Javascript\x10\v\x12\x0e\n" +
	"\n" +
	"Typescript\x10\f\x12\b\n" +
	"\x04Ruby\x10\r\x12\b\n" +
	"\x04Rust\x10\x0e*\x84\x01\n" +
	"\vASTNodeType\x12\x13\n" +
	"\x0fUastSyntaxError\x10\x00\x12\x16\n" +
	"\x12UastTransitionUnit\x10\x01\x12\x12\n" +
	"\x0eUastIdentifier\x10\x02\x12\x0f\n" +
	"\vUastLiteral\x10\x03\x12\x0f\n" +
	"\vUastKeyword\x10\x04\x12\x12\n" +
	"\x0eUastPunctuator\x10\x05*\"\n" +
	"\vASTEdgeType\x12\x13\n" +
	"\x0fUastParentChild\x10\x00B\x0fZ\rdomain/astreeb\x06proto3"

var (
	file_domain_astree_proto_rawDescOnce sync.Once
	file_domain_astree_proto_rawDescData []byte
)

func file_domain_astree_proto_rawDescGZIP() []byte {
	file_domain_astree_proto_rawDescOnce.Do(func() {
		file_domain_astree_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_astree_proto_rawDesc), len(file_domain_astree_proto_rawDesc)))
	})
	return file_domain_astree_proto_rawDescData
}

var file_domain_astree_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_domain_astree_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_astree_proto_goTypes = []any{
	(Language)(0),    // 0: domain.Language
	(ASTNodeType)(0), // 1: domain.ASTNodeType
	(ASTEdgeType)(0), // 2: domain.ASTEdgeType
	(*ASTFile)(nil),  // 3: domain.ASTFile
	(*Source)(nil),   // 4: domain.Source
	(*ASTree)(nil),   // 5: domain.ASTree
	(*ASTNode)(nil),  // 6: domain.ASTNode
	(*Position)(nil), // 7: domain.Position
	(*ASTEdge)(nil),  // 8: domain.ASTEdge
}
var file_domain_astree_proto_depIdxs = []int32{
	4,  // 0: domain.ASTFile.Source:type_name -> domain.Source
	5,  // 1: domain.ASTFile.Tree:type_name -> domain.ASTree
	0,  // 2: domain.Source.Language:type_name -> domain.Language
	0,  // 3: domain.ASTree.Language:type_name -> domain.Language
	6,  // 4: domain.ASTree.Root:type_name -> domain.ASTNode
	6,  // 5: domain.ASTree.Nodes:type_name -> domain.ASTNode
	1,  // 6: domain.ASTNode.Type:type_name -> domain.ASTNodeType
	7,  // 7: domain.ASTNode.Pos:type_name -> domain.Position
	7,  // 8: domain.ASTNode.End:type_name -> domain.Position
	8,  // 9: domain.ASTNode.Parent:type_name -> domain.ASTEdge
	8,  // 10: domain.ASTNode.Children:type_name -> domain.ASTEdge
	2,  // 11: domain.ASTEdge.Type:type_name -> domain.ASTEdgeType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_domain_astree_proto_init() }
func file_domain_astree_proto_init() {
	if File_domain_astree_proto != nil {
		return
	}
	file_domain_astree_proto_msgTypes[1].OneofWrappers = []any{}
	file_domain_astree_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_astree_proto_rawDesc), len(file_domain_astree_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_astree_proto_goTypes,
		DependencyIndexes: file_domain_astree_proto_depIdxs,
		EnumInfos:         file_domain_astree_proto_enumTypes,
		MessageInfos:      file_domain_astree_proto_msgTypes,
	}.Build()
	File_domain_astree_proto = out.File
	file_domain_astree_proto_goTypes = nil
	file_domain_astree_proto_depIdxs = nil
}
